[project]
name = "wifit3"
version = "0.1.0"
description = "Wireless Auditor TUI"
readme = "ABOUT.md"
requires-python = ">=3.10"
dependencies = [
    "loguru",
    "pydantic",
    "rich",
    "textual",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "pytest",
    "pytest-asyncio",
    "pytest-mock",
    "ruff",
    "textual-dev",
]

[tool.pytest.ini_options]
asyncio_mode = "auto"
asyncio_default_fixture_loop_scope = "function"
