[project]
name = "wifit3"
version = "0.1.0"
description = "Wireless Auditor TUI"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "libusb-package>=1.0.26.3",
    "loguru",
    "pydantic",
    "pyshark>=0.6",
    "pyusb>=1.3.1",
    "rich",
    "scapy",
    "textual",
]

[project.scripts]
wifit3 = "wifit3.__main__:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "pytest",
    "pytest-asyncio",
    "pytest-mock",
    "ruff",
    "textual-dev",
]

[tool.pytest.ini_options]
asyncio_mode = "auto"
asyncio_default_fixture_loop_scope = "function"
testpaths = ["tests"]
pythonpath = ["src"]
addopts = "--import-mode=importlib"
