"""Flat-u32 PHY_REG_PG table, extracted verbatim from the vendor source.

Generated by scripts/chips/rtl8188ftv_dkms/extract_tables.py — do not hand-edit.
Walked by phy_cond.walk_table with the driver's condition words.
"""
from __future__ import annotations

TABLE: list = [
    0x00000E08,
    0x0000FF00,
    0x00003200,
    0x0000086C,
    0xFFFFFF00,
    0x32323200,
    0x00000E00,
    0xFFFFFFFF,
    0x34363636,
    0x00000E04,
    0xFFFFFFFF,
    0x28303234,
    0x00000E10,
    0xFFFFFFFF,
    0x30343434,
    0x00000E14,
    0xFFFFFFFF,
    0x26262830,
]
