#!/usr/bin/env python3
"""Extract the reg-domain tables for the rtl8188ftv_dkms port, verbatim.

Reads the pinned vendor tree (driver_captures/captures_8188fu/driver-source)
and emits src/wifit3/chips/rtl8188ftv_dkms/regdomain.py. Re-run after any
source re-pin and diff the output.

Build config assumed (matches the capture): RTW_DEF_MODULE_REGULATORY_CERT=0,
no CONFIG_CUSTOMIZED_COUNTRY_CHPLAN_MAP, no CONFIG_80211AC_VHT — so country
rows reduce to (alpha2, chplan) and module-specific maps compile out.

Usage: uv run python scripts/chips/rtl8188ftv_dkms/extract_regdomain.py
"""
import re
from pathlib import Path

REPO = Path(__file__).resolve().parents[3]
SRC = REPO / "driver_captures" / "captures_8188fu" / "driver-source"
OUT = REPO / "src" / "wifit3" / "chips" / "rtl8188ftv_dkms" / "regdomain.py"

RD_2G = {"NULL": 0, "WORLD": 1, "ETSI1": 2, "FCC1": 3, "MKK1": 4,
         "ETSI2": 5, "GLOBAL": 6, "MKK2": 7, "FCC2": 8}
RD_5G = {"NULL": 0, "ETSI1": 1, "ETSI2": 2, "ETSI3": 3, "FCC1": 4, "FCC2": 5,
         "FCC3": 6, "FCC4": 7, "FCC5": 8, "FCC6": 9, "FCC7": 10, "KCC1": 11,
         "MKK1": 12, "MKK2": 13, "MKK3": 14, "NCC1": 15, "NCC2": 16,
         "NCC3": 17, "ETSI4": 18, "ETSI5": 19, "FCC8": 20, "ETSI6": 21,
         "ETSI7": 22, "ETSI8": 23, "ETSI9": 24, "ETSI10": 25, "ETSI11": 26,
         "NCC4": 27, "ETSI12": 28, "FCC9": 29, "ETSI13": 30, "FCC10": 31,
         "MKK4": 32, "ETSI14": 33, "OLD_FCC1": 34, "OLD_NCC1": 35,
         "OLD_KCC1": 36}
LMT = {"FCC": 0, "MKK": 1, "ETSI": 2, "WW": 3}


def extract_country(text):
    start = text.index("static const struct country_chplan country_chplan_map[] = {")
    end = text.index("};", start)
    rows = re.findall(r'COUNTRY_CHPLAN_ENT\("([A-Z]{2})",\s*(0x[0-9A-Fa-f]+),', text[start:end])
    return [(a2, int(ch, 16)) for a2, ch in rows]


def extract_planmap(text):
    start = text.index("static RT_CHANNEL_PLAN_MAP\tRTW_ChannelPlanMap[] = {")
    end = text.index("};", start)
    rows = re.findall(r"\{(RTW_RD_2G_\w+),\s*(RTW_RD_5G_\w+),\s*TXPWR_LMT_(\w+)\},",
                      text[start:end])
    out = []
    for g2, g5, lmt in rows:
        out.append((RD_2G[g2.replace("RTW_RD_2G_", "")],
                    RD_5G[g5.replace("RTW_RD_5G_", "")], LMT[lmt]))
    return out


def main():
    rf = (SRC / "core" / "rtw_rf.c").read_text()
    mlme = (SRC / "core" / "rtw_mlme_ext.c").read_text()
    country = extract_country(rf)
    planmap = extract_planmap(mlme)
    lines = [
        '"""Reg-domain tables, extracted verbatim from the vendor source.',
        "",
        "Generated by scripts/chips/rtl8188ftv_dkms/extract_regdomain.py — do not hand-edit.",
        'Source: driver_captures/captures_8188fu/driver-source @ 799fa0b.',
        'Build: RTW_DEF_MODULE_REGULATORY_CERT=0, no CUSTOMIZED map, no 80211AC_VHT.',
        '"""',
        "from __future__ import annotations",
        "",
        "# (alpha2, chplan): core/rtw_rf.c country_chplan_map",
        "COUNTRY_CHPLAN: list = [",
    ]
    lines += [f"    ({a2!r}, 0x{ch:02X})," for a2, ch in country]
    lines += [
        "]",
        "",
        "# (rd2g, rd5g, txpwr_lmt): core/rtw_mlme_ext.c RTW_ChannelPlanMap, index = chplan id",
        "CHANNEL_PLAN_MAP: list = [",
    ]
    lines += [f"    ({g2}, {g5}, {lmt})," for g2, g5, lmt in planmap]
    lines += ["]", ""]
    OUT.write_text("\n".join(lines))
    print(f"wrote {OUT}: {len(country)} countries, {len(planmap)} chplan rows")


if __name__ == "__main__":
    main()
