#!/usr/bin/env python3
"""Extract the phydm init tables for the rtl8188ftv_dkms port, verbatim.

Reads the pinned vendor tree (driver_captures/captures_8188fu/driver-source)
and emits one flat-u32 Python table per phydm array. Re-run after any source
re-pin and diff the output.

Usage: uv run python scripts/chips/rtl8188ftv_dkms/extract_tables.py
"""
import re
from pathlib import Path

REPO = Path(__file__).resolve().parents[3]
SRC = REPO / "driver_captures" / "captures_8188fu" / "driver-source"
OUTDIR = REPO / "src" / "wifit3" / "chips" / "rtl8188ftv_dkms"

TABLES = [
    ("hal/phydm/rtl8188f/halhwimg8188f_mac.c",
     "Array_MP_8188F_MAC_REG", "mac_reg_tbl.py", "MAC_REG"),
    ("hal/phydm/rtl8188f/halhwimg8188f_bb.c",
     "Array_MP_8188F_AGC_TAB", "bb_agc_tab_tbl.py", "AGC_TAB"),
    ("hal/phydm/rtl8188f/halhwimg8188f_bb.c",
     "Array_MP_8188F_PHY_REG", "bb_phy_reg_tbl.py", "PHY_REG"),
    ("hal/phydm/rtl8188f/halhwimg8188f_bb.c",
     "Array_MP_8188F_PHY_REG_PG", "bb_phy_reg_pg_tbl.py", "PHY_REG_PG"),
    ("hal/phydm/rtl8188f/halhwimg8188f_rf.c",
     "Array_MP_8188F_RadioA", "rf_radio_a_tbl.py", "RadioA"),
]

# (array, out-key) swing tables filled by
# ODM_ReadAndConfig_MP_8188F_TxPowerTrack_USB (pure-sw memcpy, no wire).
SWING_TABLES = [
    "2GA_P", "2GA_N", "2GB_P", "2GB_N",
    "2GCCKA_P", "2GCCKA_N", "2GCCKB_P", "2GCCKB_N",
    "5GA_P", "5GA_N", "5GB_P", "5GB_N",
]


def extract(path: Path, array: str) -> list[int]:
    text = (SRC / path).read_text()
    m = re.search(re.escape(array) + r"\[\] = \{(.*?)\};", text, re.S)
    assert m, f"{array} not found in {path}"
    return [int(x, 0) for x in re.findall(r"0x[0-9A-Fa-f]+|\b\d+\b", m.group(1))]


def extract_swing(text: str, key: str) -> list:
    m = re.search(r"gDeltaSwingTableIdx_MP_" + key + r"_TxPowerTrack_USB_8188F\[\]\[.*?\] = \{(.*?)\};",
                  text, re.S)
    if m:
        rows = []
        for row in re.findall(r"\{([^{}]+)\}", m.group(1)):
            rows.append([int(x) for x in re.findall(r"\b\d+\b", row)])
        assert rows, f"swing table {key} has no rows"
        return rows
    m = re.search(r"gDeltaSwingTableIdx_MP_" + key + r"_TxPowerTrack_USB_8188F\[\]\s*= \{(.*?)\};",
                  text, re.S)
    assert m, f"swing table {key} not found"
    return [int(x) for x in re.findall(r"\b\d+\b", m.group(1))]


def emit_swings():
    text = (SRC / "hal/phydm/rtl8188f/halhwimg8188f_rf.c").read_text()
    lines = [
        '"""TxPowerTrack_USB swing tables, extracted verbatim from the vendor source.',
        "",
        "Generated by scripts/chips/rtl8188ftv_dkms/extract_tables.py"
        " — do not hand-edit.",
        "Pure-sw memcpy targets of ODM_ReadAndConfig_MP_8188F_TxPowerTrack_USB;",
        "no wire. Keyed by band/path/N/P like the driver's RFCalibrateInfo.",
        '"""',
        "from __future__ import annotations",
        "",
        "TABLES: dict = {",
    ]
    for key in SWING_TABLES:
        lines.append(f"    {key!r}: {extract_swing(text, key)!r},")
    lines += ["}", ""]
    (OUTDIR / "rf_txpwr_track_tbl.py").write_text("\n".join(lines))
    print(f"wrote rf_txpwr_track_tbl.py: {len(SWING_TABLES)} tables")


def main():
    for path, array, outfile, _label in TABLES:
        words = extract(Path(path), array)
        lines = [
            f'"""Flat-u32 {_label} table, extracted verbatim from the vendor source.',
            "",
            "Generated by scripts/chips/rtl8188ftv_dkms/extract_tables.py"
            " — do not hand-edit.",
            "Walked by phy_cond.walk_table with the driver's condition words.",
            '"""',
            "from __future__ import annotations",
            "",
            "TABLE: list = [",
        ]
        lines += [f"    0x{w:08X}," for w in words]
        lines += ["]", ""]
        (OUTDIR / outfile).write_text("\n".join(lines))
        print(f"wrote {outfile}: {len(words)} words")
    emit_swings()


if __name__ == "__main__":
    main()
